# Generated by Django 3.2.18 on 2023-05-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_followermodel_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ('-created_on',)},
        ),
        migrations.RemoveField(
            model_name='likemodel',
            name='is_like',
        ),
    ]
